security:
    # Gestion du hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Gestion du provider utilisateur
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator

            # Gestion de la connexion
            form_login:
                login_path: app_login       # Page de connexion
                check_path: app_login       # Symfony gère cette route automatiquement
                default_target_path: app_home  # Redirige l'utilisateur après connexion

            entry_point: form_login
            
            # Gestion de la déconnexion
            logout:
                path: app_logout
                target: app_landing  # Redirection vers la page de départ

            # Gestion de la fonctionnalité "Se souvenir de moi"
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

            # switch_user (optionnel mais non activé par défaut)
            # switch_user: true

    # Gestion des accès aux différentes parties du site
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/app, roles: ROLE_USER }
        - { path: ^/settings, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }   # Permet l'accès à la page de connexion
        - { path: ^/register, roles: PUBLIC_ACCESS } # Permet l'accès à la page d'inscription
        - { path: ^/logout, roles: PUBLIC_ACCESS }   # Permet la déconnexion
        - { path: ^/, roles: PUBLIC_ACCESS }         # Permet l'accès à la landing page

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # Valeur minimale pour bcrypt
                time_cost: 3  # Valeur minimale pour argon
                memory_cost: 10  # Valeur minimale pour argon
