framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: null
        cookie_secure: auto  # 🔧 permet d'éviter la redirection HTTPS locale

    #esi: true
    #fragments: true

    http_method_override: true
    trusted_proxies: ~
    trusted_hosts: ~

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
