services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  flask-api: # Ajout minimal pour le service Flask
    volumes:
      - ./fsrs-api:/app # Monte le répertoire local pour le hot-reloading
    environment:
      FLASK_ENV: development # Active le mode développement pour Flask
