controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_landing:
    path: /landing
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'landing/index.html.twig'
